import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mirrorfly_plugin/builder.dart';
import 'package:mirrorfly_plugin/fly_chat_method_channel.dart';
import 'package:mirrorfly_plugin/mirrorflychat.dart';
import 'package:mirrorfly_plugin/model/profile_update.dart';
import 'package:mirrorfly_plugin/model/recent_chat.dart';
import 'package:mirrorfly_plugin/model/register_model.dart' as register;
import 'package:mirrorfly_plugin/model/profile_model.dart' as profile;

void main() {
  MethodChannelFlyChatFlutter platform = MethodChannelFlyChatFlutter();
  const MethodChannel channel = MethodChannel('contus.mirrorfly/flyChat');
  final List<MethodCall> log = <MethodCall>[];

  TestWidgetsFlutterBinding.ensureInitialized();

  setUp(() {
    TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger
        .setMockMethodCallHandler(
      channel,
      (MethodCall methodCall) async {
        log.add(methodCall);
        return '42';
      },
    );
  });

  tearDown(() {
    log.clear();
    TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger
        .setMockMethodCallHandler(channel, null);
  });

  test('init', () async {
    await platform.init(ChatBuilder(
        domainBaseUrl: 'domainBaseUrl',
        licenseKey: 'licenseKey',
        iOSContainerID: ''));
  });

  test('registerUser',(){
    var output = """{
  "message": "Register Trial API Success",
  "data": {
    "config": {
      "googleTranslate": "AIzaSyCdwzAZR6tx8KB-2dMn0KzSI1V0LpsYdH0",
      "isLiveStreamingEnabled": false,
      "recentchatSearch": true,
      "locationAttachment": true,
      "deleteMessage": true,
      "xmppDomain": "xmpp-uikit-qa.contus.us",
      "audioAttachment": true,
      "attachment": true,
      "fileSizeLimit": 2000,
      "adminUser": "123456789",
      "privateTime": 1,
      "xmppHost": "xmpp-uikit-qa.contus.us",
      "groupCall": true,
      "videoAttachment": true,
      "videoLimit": 40,
      "viewAllMedias": true,
      "iv": "ddc0f15cc2c90fca",
      "deleteChat": true,
      "signalServerDomain": "https://signal-uikit-qa.contus.us/",
      "turns": [
        {
          "turn": "turn:stun.contus.us:3478",
          "username": "contus",
          "password": "SAE@admin"
        }
      ],
      "sipServer": null,
      "callRoutingServer": "wss://janus.contus.us/",
      "imageAttachment": true,
      "xmppPortWeb": "5280",
      "translation": true,
      "domain": "@contus.in",
      "stuns": [
        "stun:stun.contus.us"
      ],
      "documentAttachment": true,
      "sipcallEnabled": false,
      "xmppPort": 5222,
      "contactAttachment": true,
      "ivProfile": "ckIjaccWBoMNvxdbql8LJ2dmKqT5bp",
      "chatBackupFrequency": null,
      "one2oneCall": true,
      "chatHistory": true,
      "audioLimit": 60,
      "starMessage": true,
      "sdkUrl": "NULL",
      "recallTime": 60,
      "notificationHelpUrl": "",
      "pinExpireDays": 31,
      "pinTimeOut": 32,
      "chatBackupType": null,
      "groupChat": true,
      "report": true,
      "clearChat": true,
      "liveStreamingSignalServer": null,
      "block": true
    },
    "message": "User Registered Successfully",
    "password": "poqc9zYluQhVU8C",
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0ZW1wRGF0YSI6ImpYVkpFWmMxQjc5WTJLdXA1OFI4IiwiaXNzIjoiYXV0aDAiLCJleHAiOjE3MDQ0NDY3MDR9.oxRFyraDlakzmHUjwQW2UlUWCsFb5acs9VKSQ2BvfdM",
    "username": "919876543210",
    "userJid": "919876543210@xmpp-uikit-qa.contus.us",
    "isProfileUpdated": true,
    "newLogin": true,
    "isExisting": true
  },
  "is_new_user": true
}""";
    var response = register.convertJsonFromString(output);
    debugPrint(response);
  });

  test('getUserProfile',(){
    var output1 = """{
    "data": {
        "colorCode": "",
        "contactType": "local",
        "email": "goat@ags.com",
        "groupCreatedTime": 0,
        "image": "9198765432101704350526763myM3aN80GCbYQooh0df3.jpg",
        "imageLocalPath": "",
        "imagePrivacyFlag": false,
        "isBlocked": false,
        "isBlockedByAdmin": false,
        "isBlockedMe": false,
        "isGroupAdmin": false,
        "isGroupInOfflineMode": false,
        "isItSavedContact": false,
        "isMuted": false,
        "isSelected": false,
        "isSyncNeeded": true,
        "jid": "919876543210@xmpp-uikit-qa.contus.us",
        "lastSeenPrivacyFlag": false,
        "mobileNumber": "9876543210",
        "mobileNUmberPrivacyFlag": false,
        "name": "GOAT",
        "nickName": "GOAT",
        "profileChatType": "singlechat",
        "status": "I am in Mirror Fly",
        "statusPrivacyFlag": false,
        "thumbImage": ""
    },
    "status": true
}""";
    var response = profile.convertProfileJsonFromString(output1);
    debugPrint(response);
  });

  test("updateProfile",(){
    var output = """{
  "status": true,
  "message": "Profile Update Success",
  "data": {
    "status": "I am in Mirror Fly",
    "thumbImage": "",
    "image": "9198765432101704350526763myM3aN80GCbYQooh0df3.jpg",
    "email": "goat@ags.com",
    "mobileNumber": "9876543210",
    "jid": "919876543210@xmpp-uikit-qa.contus.us",
    "nickName": "GOAT",
    "name": "GOAT"
  }
}""";
    var response = convertProfileUpdateJsonFromString(output);
    debugPrint(response);
  });

  test("getRecentChatHistory",(){
    var output = """{
  "data": [
    {
      "isBlockedByAdmin": false,
      "metaData": [],
      "isGroup": false,
      "profileImage": "",
      "nickName": "",
      "lastMessageId": "473ae99ba30441f7950c14fd3f46b4131664098783",
      "isPrivateChat": false,
      "lastMessageTime": 1704435974000000,
      "isItSavedContact": false,
      "isConversationUnRead": false,
      "lastMessageStatus": 1,
      "profileThumbImage": "",
      "lastMessageContent": "",
      "isSelected": false,
      "jid": "918765432100@xmpp-uikit-qa.contus.us",
      "profileType": "singlechat",
      "lastMessageType": "text",
      "isGroupInOfflineMode": false,
      "isDeletedUser": false,
      "isBroadCast": false,
      "isChatArchived": false,
      "topicID": "",
      "isMentionedUser": false,
      "mentionedUsersIds": [],
      "isChatPinned": false,
      "isLastMessageRecalledByUser": false,
      "isBlocked": false,
      "isLastMessageSentByMe": true,
      "profileName": "",
      "isMuted": false,
      "unreadMessageCount": 0,
      "isBlockedMe": false
    },
    {
      "isBlockedByAdmin": false,
      "metaData": [],
      "isGroup": true,
      "profileImage": "9198765432101702537854842Y87OcS4KIk5RI2A70vr7.jpg",
      "nickName": "Group Call",
      "lastMessageId": "0c0a6e8f310d4854a98e3d3c22c1120b1704181114",
      "isPrivateChat": false,
      "lastMessageTime": 1704181110713757,
      "isItSavedContact": false,
      "isConversationUnRead": false,
      "lastMessageStatus": 1,
      "profileThumbImage": "",
      "lastMessageContent": "",
      "isSelected": false,
      "jid": "1697094967970919789482015@mix.xmpp-uikit-qa.contus.us",
      "profileType": "groupchat",
      "lastMessageType": "text",
      "isGroupInOfflineMode": false,
      "isDeletedUser": false,
      "isBroadCast": false,
      "isChatArchived": false,
      "topicID": "",
      "isMentionedUser": false,
      "mentionedUsersIds": [],
      "isChatPinned": false,
      "isLastMessageRecalledByUser": false,
      "isBlocked": false,
      "isLastMessageSentByMe": true,
      "profileName": "Group Call",
      "isMuted": false,
      "unreadMessageCount": 0,
      "isBlockedMe": false
    },
    {
      "isBlockedByAdmin": false,
      "metaData": [],
      "isGroup": false,
      "profileImage": "91888345246117042028323628560k3VCf8O1J0BCE0o3.jpg",
      "nickName": "Jarvis",
      "lastMessageId": "12e477433a864a9da13bcc88d0560ef61703750415",
      "isPrivateChat": false,
      "lastMessageTime": 1703750413647776,
      "isItSavedContact": false,
      "isConversationUnRead": false,
      "lastMessageStatus": 1,
      "profileThumbImage": "",
      "lastMessageContent": "",
      "isSelected": false,
      "jid": "918883452461@xmpp-uikit-qa.contus.us",
      "profileType": "singlechat",
      "lastMessageType": "text",
      "isGroupInOfflineMode": false,
      "isDeletedUser": false,
      "isBroadCast": false,
      "isChatArchived": false,
      "topicID": "",
      "isMentionedUser": false,
      "mentionedUsersIds": [],
      "isChatPinned": false,
      "isLastMessageRecalledByUser": false,
      "isBlocked": false,
      "isLastMessageSentByMe": false,
      "profileName": "Jarvis",
      "isMuted": false,
      "unreadMessageCount": 0,
      "isBlockedMe": false
    },
    {
      "isBlockedByAdmin": false,
      "metaData": [],
      "isGroup": false,
      "profileImage": "",
      "nickName": "jeeva t333",
      "lastMessageId": "2aa0ad8c69824df89959d52b179dee4d1702989861",
      "isPrivateChat": false,
      "lastMessageTime": 1702989860164597,
      "isItSavedContact": false,
      "isConversationUnRead": false,
      "lastMessageStatus": 1,
      "profileThumbImage": "",
      "lastMessageContent": "",
      "isSelected": false,
      "jid": "919025139260@xmpp-uikit-qa.contus.us",
      "profileType": "singlechat",
      "lastMessageType": "text",
      "isGroupInOfflineMode": false,
      "isDeletedUser": false,
      "isBroadCast": false,
      "isChatArchived": false,
      "topicID": "",
      "isMentionedUser": false,
      "mentionedUsersIds": [],
      "isChatPinned": false,
      "isLastMessageRecalledByUser": false,
      "isBlocked": false,
      "isLastMessageSentByMe": false,
      "profileName": "jeeva t333",
      "isMuted": false,
      "unreadMessageCount": 0,
      "isBlockedMe": false
    },
    {
      "isBlockedByAdmin": false,
      "metaData": [],
      "isGroup": false,
      "profileImage": "",
      "nickName": "lTeMIw0eK0V+7M1tZxajdQ==",
      "lastMessageId": "9816b19a9e314ff6b5baf2bded9ff0441701327239",
      "isPrivateChat": false,
      "lastMessageTime": 1701328105577720,
      "isItSavedContact": false,
      "isConversationUnRead": false,
      "lastMessageStatus": 1,
      "profileThumbImage": "",
      "lastMessageContent": "",
      "isSelected": false,
      "jid": "918072577879@xmpp-uikit-qa.contus.us",
      "profileType": "singlechat",
      "lastMessageType": "text",
      "isGroupInOfflineMode": false,
      "isDeletedUser": false,
      "isBroadCast": false,
      "isChatArchived": false,
      "topicID": "",
      "isMentionedUser": false,
      "mentionedUsersIds": [],
      "isChatPinned": false,
      "isLastMessageRecalledByUser": false,
      "isBlocked": false,
      "isLastMessageSentByMe": false,
      "profileName": "lTeMIw0eK0V+7M1tZxajdQ==",
      "isMuted": false,
      "unreadMessageCount": 0,
      "isBlockedMe": false
    },
    {
      "isBlockedByAdmin": false,
      "metaData": [],
      "isGroup": true,
      "profileImage": "",
      "nickName": "RN Test Web",
      "lastMessageId": "16981132390819372153",
      "isPrivateChat": false,
      "lastMessageTime": 1701154051722815,
      "isItSavedContact": false,
      "isConversationUnRead": false,
      "lastMessageStatus": 1,
      "profileThumbImage": "",
      "lastMessageContent": "",
      "isSelected": false,
      "jid": "df470b86-5cc7-41be-9881-32955f1e5355@mix.xmpp-uikit-qa.contus.us",
      "profileType": "groupchat",
      "lastMessageType": "text",
      "isGroupInOfflineMode": false,
      "isDeletedUser": false,
      "isBroadCast": false,
      "isChatArchived": false,
      "topicID": "",
      "isMentionedUser": false,
      "mentionedUsersIds": [],
      "isChatPinned": false,
      "isLastMessageRecalledByUser": false,
      "isBlocked": false,
      "isLastMessageSentByMe": false,
      "profileName": "RN Test Web",
      "isMuted": false,
      "unreadMessageCount": 0,
      "isBlockedMe": false
    },
    {
      "isBlockedByAdmin": false,
      "metaData": [],
      "isGroup": true,
      "profileImage": "",
      "nickName": "RN test grp",
      "lastMessageId": "6d95b404-c02c-49f2-9196-c50b93efcba4",
      "isPrivateChat": false,
      "lastMessageTime": 1701088125230130,
      "isItSavedContact": false,
      "isConversationUnRead": false,
      "lastMessageStatus": 1,
      "profileThumbImage": "",
      "lastMessageContent": "",
      "isSelected": false,
      "jid": "bd0f8e5f-121d-419a-9265-6040a1ea8063@mix.xmpp-uikit-qa.contus.us",
      "profileType": "groupchat",
      "lastMessageType": "text",
      "isGroupInOfflineMode": false,
      "isDeletedUser": false,
      "isBroadCast": false,
      "isChatArchived": false,
      "topicID": "",
      "isMentionedUser": false,
      "mentionedUsersIds": [],
      "isChatPinned": false,
      "isLastMessageRecalledByUser": false,
      "isBlocked": false,
      "isLastMessageSentByMe": false,
      "profileName": "RN test grp",
      "isMuted": false,
      "unreadMessageCount": 0,
      "isBlockedMe": false
    },
    {
      "isBlockedByAdmin": false,
      "metaData": [],
      "isGroup": false,
      "profileImage": "",
      "nickName": "1tP1PHbqO2IjkuYqGGdZfw==",
      "lastMessageId": "e58da080456948be874dbd6a4b6bd2aa1701069858",
      "isPrivateChat": false,
      "lastMessageTime": 1701069858848512,
      "isItSavedContact": false,
      "isConversationUnRead": false,
      "lastMessageStatus": 1,
      "profileThumbImage": "",
      "lastMessageContent": "",
      "isSelected": false,
      "jid": "919874563210@xmpp-uikit-qa.contus.us",
      "profileType": "singlechat",
      "lastMessageType": "text",
      "isGroupInOfflineMode": false,
      "isDeletedUser": false,
      "isBroadCast": false,
      "isChatArchived": false,
      "topicID": "",
      "isMentionedUser": false,
      "mentionedUsersIds": [],
      "isChatPinned": false,
      "isLastMessageRecalledByUser": false,
      "isBlocked": false,
      "isLastMessageSentByMe": true,
      "profileName": "1tP1PHbqO2IjkuYqGGdZfw==",
      "isMuted": false,
      "unreadMessageCount": 0,
      "isBlockedMe": false
    },
    {
      "isBlockedByAdmin": false,
      "metaData": [],
      "isGroup": true,
      "profileImage": "",
      "nickName": "Hhshs",
      "lastMessageId": "3587298286554006284",
      "isPrivateChat": false,
      "lastMessageTime": 1700813018352932,
      "isItSavedContact": false,
      "isConversationUnRead": false,
      "lastMessageStatus": 1,
      "profileThumbImage": "",
      "lastMessageContent": "",
      "isSelected": false,
      "jid": "1700736685850919789482015@mix.xmpp-uikit-qa.contus.us",
      "profileType": "groupchat",
      "lastMessageType": "text",
      "isGroupInOfflineMode": false,
      "isDeletedUser": false,
      "isBroadCast": false,
      "isChatArchived": false,
      "topicID": "",
      "isMentionedUser": false,
      "mentionedUsersIds": [],
      "isChatPinned": false,
      "isLastMessageRecalledByUser": false,
      "isBlocked": false,
      "isLastMessageSentByMe": false,
      "profileName": "Hhshs",
      "isMuted": false,
      "unreadMessageCount": 0,
      "isBlockedMe": false
    },
    {
      "isBlockedByAdmin": false,
      "metaData": [],
      "isGroup": false,
      "profileImage": "",
      "nickName": "KOQQuDLlVbP7oxjQf6VegQ==",
      "lastMessageId": "3cee7a1c96564f8bbd88365c485067a01696846755",
      "isPrivateChat": false,
      "lastMessageTime": 1696846756549992,
      "isItSavedContact": false,
      "isConversationUnRead": false,
      "lastMessageStatus": 1,
      "profileThumbImage": "",
      "lastMessageContent": "",
      "isSelected": false,
      "jid": "919585642839@xmpp-uikit-qa.contus.us",
      "profileType": "singlechat",
      "lastMessageType": "text",
      "isGroupInOfflineMode": false,
      "isDeletedUser": false,
      "isBroadCast": false,
      "isChatArchived": false,
      "topicID": "",
      "isMentionedUser": false,
      "mentionedUsersIds": [],
      "isChatPinned": false,
      "isLastMessageRecalledByUser": false,
      "isBlocked": false,
      "isLastMessageSentByMe": false,
      "profileName": "KOQQuDLlVbP7oxjQf6VegQ==",
      "isMuted": false,
      "unreadMessageCount": 0,
      "isBlockedMe": false
    },
    {
      "isBlockedByAdmin": false,
      "metaData": [],
      "isGroup": false,
      "profileImage": "91852669758117019463828974kB4nzu5Mo00T0mM2YM7.jpg",
      "nickName": "Gurudharan",
      "lastMessageId": "43f48686279b4bc3a5ff35bbb1fb0bc8",
      "isPrivateChat": false,
      "lastMessageTime": 1696593914010441,
      "isItSavedContact": false,
      "isConversationUnRead": false,
      "lastMessageStatus": 1,
      "profileThumbImage": "",
      "lastMessageContent": "",
      "isSelected": false,
      "jid": "918526697581@xmpp-uikit-qa.contus.us",
      "profileType": "singlechat",
      "lastMessageType": "text",
      "isGroupInOfflineMode": false,
      "isDeletedUser": false,
      "isBroadCast": false,
      "isChatArchived": false,
      "topicID": "",
      "isMentionedUser": false,
      "mentionedUsersIds": [],
      "isChatPinned": false,
      "isLastMessageRecalledByUser": false,
      "isBlocked": false,
      "isLastMessageSentByMe": true,
      "profileName": "Gurudharan",
      "isMuted": false,
      "unreadMessageCount": 0,
      "isBlockedMe": false
    },
    {
      "isBlockedByAdmin": false,
      "metaData": [],
      "isGroup": false,
      "profileImage": "",
      "nickName": "KWuma0uBeXTv9IpX7zgeDA==",
      "lastMessageId": "6b61761844fb4de8aa1497e82a1b25fa1695123278",
      "isPrivateChat": false,
      "lastMessageTime": 1695123278557698,
      "isItSavedContact": false,
      "isConversationUnRead": false,
      "lastMessageStatus": 1,
      "profileThumbImage": "",
      "lastMessageContent": "",
      "isSelected": false,
      "jid": "919790321115@xmpp-uikit-qa.contus.us",
      "profileType": "singlechat",
      "lastMessageType": "text",
      "isGroupInOfflineMode": false,
      "isDeletedUser": false,
      "isBroadCast": false,
      "isChatArchived": false,
      "topicID": "",
      "isMentionedUser": false,
      "mentionedUsersIds": [],
      "isChatPinned": false,
      "isLastMessageRecalledByUser": false,
      "isBlocked": false,
      "isLastMessageSentByMe": true,
      "profileName": "KWuma0uBeXTv9IpX7zgeDA==",
      "isMuted": false,
      "unreadMessageCount": 0,
      "isBlockedMe": false
    },
    {
      "isBlockedByAdmin": false,
      "metaData": [],
      "isGroup": false,
      "profileImage": "",
      "nickName": "oPXicB9fCw7pd0LM+ML5tA==",
      "lastMessageId": "8681655c55f547bcb7c09bdd0c7e187a1695117929",
      "isPrivateChat": false,
      "lastMessageTime": 1695117929734089,
      "isItSavedContact": false,
      "isConversationUnRead": false,
      "lastMessageStatus": 1,
      "profileThumbImage": "",
      "lastMessageContent": "",
      "isSelected": false,
      "jid": "919790321118@xmpp-uikit-qa.contus.us",
      "profileType": "singlechat",
      "lastMessageType": "text",
      "isGroupInOfflineMode": false,
      "isDeletedUser": false,
      "isBroadCast": false,
      "isChatArchived": false,
      "topicID": "",
      "isMentionedUser": false,
      "mentionedUsersIds": [],
      "isChatPinned": false,
      "isLastMessageRecalledByUser": false,
      "isBlocked": false,
      "isLastMessageSentByMe": true,
      "profileName": "oPXicB9fCw7pd0LM+ML5tA==",
      "isMuted": false,
      "unreadMessageCount": 0,
      "isBlockedMe": false
    },
    {
      "isBlockedByAdmin": false,
      "metaData": [],
      "isGroup": false,
      "profileImage": "",
      "nickName": "CpuBDYgnA5SP+M5DpYVNsg==",
      "lastMessageId": "b1c2a0301f44455da4340ee8c06db1491694781214",
      "isPrivateChat": false,
      "lastMessageTime": 1694781214735864,
      "isItSavedContact": false,
      "isConversationUnRead": false,
      "lastMessageStatus": 1,
      "profileThumbImage": "",
      "lastMessageContent": "",
      "isSelected": false,
      "jid": "918124518868@xmpp-uikit-qa.contus.us",
      "profileType": "singlechat",
      "lastMessageType": "text",
      "isGroupInOfflineMode": false,
      "isDeletedUser": false,
      "isBroadCast": false,
      "isChatArchived": false,
      "topicID": "",
      "isMentionedUser": false,
      "mentionedUsersIds": [],
      "isChatPinned": false,
      "isLastMessageRecalledByUser": false,
      "isBlocked": false,
      "isLastMessageSentByMe": false,
      "profileName": "CpuBDYgnA5SP+M5DpYVNsg==",
      "isMuted": false,
      "unreadMessageCount": 0,
      "isBlockedMe": false
    },
    {
      "isBlockedByAdmin": false,
      "metaData": [],
      "isGroup": true,
      "profileImage": "",
      "nickName": "notification new😄",
      "lastMessageId": "07b75af4f4824d6699f9103297c68ca8",
      "isPrivateChat": false,
      "lastMessageTime": 1694174872108138,
      "isItSavedContact": false,
      "isConversationUnRead": false,
      "lastMessageStatus": 1,
      "profileThumbImage": "",
      "lastMessageContent": "",
      "isSelected": false,
      "jid": "1691249305571919894940560@mix.xmpp-uikit-qa.contus.us",
      "profileType": "groupchat",
      "lastMessageType": "text",
      "isGroupInOfflineMode": false,
      "isDeletedUser": false,
      "isBroadCast": false,
      "isChatArchived": false,
      "topicID": "",
      "isMentionedUser": false,
      "mentionedUsersIds": [],
      "isChatPinned": false,
      "isLastMessageRecalledByUser": false,
      "isBlocked": false,
      "isLastMessageSentByMe": false,
      "profileName": "notification new😄",
      "isMuted": false,
      "unreadMessageCount": 0,
      "isBlockedMe": false
    },
    {
      "isBlockedByAdmin": false,
      "metaData": [],
      "isGroup": true,
      "profileImage": "",
      "nickName": "minify",
      "lastMessageId": "15403096817487890243",
      "isPrivateChat": false,
      "lastMessageTime": 1693312319163636,
      "isItSavedContact": false,
      "isConversationUnRead": false,
      "lastMessageStatus": 1,
      "profileThumbImage": "",
      "lastMessageContent": "",
      "isSelected": false,
      "jid": "1692338963696919876543210@mix.xmpp-uikit-qa.contus.us",
      "profileType": "groupchat",
      "lastMessageType": "text",
      "isGroupInOfflineMode": false,
      "isDeletedUser": false,
      "isBroadCast": false,
      "isChatArchived": false,
      "topicID": "",
      "isMentionedUser": false,
      "mentionedUsersIds": [],
      "isChatPinned": false,
      "isLastMessageRecalledByUser": false,
      "isBlocked": false,
      "isLastMessageSentByMe": true,
      "profileName": "minify",
      "isMuted": false,
      "unreadMessageCount": 0,
      "isBlockedMe": false
    },
    {
      "isBlockedByAdmin": false,
      "metaData": [],
      "isGroup": false,
      "profileImage": "",
      "nickName": "Deepika  74",
      "lastMessageId": "e7b53843b604431cb6d5603de5f88bd9",
      "isPrivateChat": false,
      "lastMessageTime": 1692187636856649,
      "isItSavedContact": true,
      "isConversationUnRead": false,
      "lastMessageStatus": 1,
      "profileThumbImage": "",
      "lastMessageContent": "",
      "isSelected": false,
      "jid": "917418983122@xmpp-uikit-qa.contus.us",
      "profileType": "singlechat",
      "lastMessageType": "text",
      "isGroupInOfflineMode": false,
      "isDeletedUser": false,
      "isBroadCast": false,
      "isChatArchived": false,
      "topicID": "",
      "isMentionedUser": false,
      "mentionedUsersIds": [],
      "isChatPinned": false,
      "isLastMessageRecalledByUser": false,
      "isBlocked": false,
      "isLastMessageSentByMe": false,
      "profileName": "Deepika  74",
      "isMuted": false,
      "unreadMessageCount": 0,
      "isBlockedMe": false
    },
    {
      "isBlockedByAdmin": false,
      "metaData": [],
      "isGroup": false,
      "profileImage": "",
      "nickName": "",
      "lastMessageId": "f7106498f00f40d592a14562b0a281ec1692006103",
      "isPrivateChat": false,
      "lastMessageTime": 1692006105327649,
      "isItSavedContact": false,
      "isConversationUnRead": false,
      "lastMessageStatus": 3,
      "profileThumbImage": "",
      "lastMessageContent": "",
      "isSelected": false,
      "jid": "919283746510@xmpp-uikit-qa.contus.us",
      "profileType": "singlechat",
      "lastMessageType": "text",
      "isGroupInOfflineMode": false,
      "isDeletedUser": false,
      "isBroadCast": false,
      "isChatArchived": false,
      "topicID": "",
      "isMentionedUser": false,
      "mentionedUsersIds": [],
      "isChatPinned": false,
      "isLastMessageRecalledByUser": false,
      "isBlocked": false,
      "isLastMessageSentByMe": false,
      "profileName": "",
      "isMuted": false,
      "unreadMessageCount": 0,
      "isBlockedMe": false
    },
    {
      "isBlockedByAdmin": false,
      "metaData": [],
      "isGroup": false,
      "profileImage": "",
      "nickName": "g4BNJQ9efIyoL1bTTwFZAKdtCn85OZuePnKVLyqAaA7vGwiFAM2Jug7u16wggYCe",
      "lastMessageId": "2b9b0cd2314943be89cd5dfa9d1ba9131691048062",
      "isPrivateChat": false,
      "lastMessageTime": 1691048062787581,
      "isItSavedContact": false,
      "isConversationUnRead": false,
      "lastMessageStatus": 1,
      "profileThumbImage": "",
      "lastMessageContent": "",
      "isSelected": false,
      "jid": "917708226683@xmpp-uikit-qa.contus.us",
      "profileType": "singlechat",
      "lastMessageType": "text",
      "isGroupInOfflineMode": false,
      "isDeletedUser": false,
      "isBroadCast": false,
      "isChatArchived": false,
      "topicID": "",
      "isMentionedUser": false,
      "mentionedUsersIds": [],
      "isChatPinned": false,
      "isLastMessageRecalledByUser": false,
      "isBlocked": false,
      "isLastMessageSentByMe": false,
      "profileName": "g4BNJQ9efIyoL1bTTwFZAKdtCn85OZuePnKVLyqAaA7vGwiFAM2Jug7u16wggYCe",
      "isMuted": false,
      "unreadMessageCount": 0,
      "isBlockedMe": false
    },
    {
      "isBlockedByAdmin": false,
      "metaData": [],
      "isGroup": false,
      "profileImage": "",
      "nickName": "Iv0XaLzMwy922KFjAyYpCQ==",
      "lastMessageId": "ac2a3f27adf04201b3198519ee116c671690974960",
      "isPrivateChat": false,
      "lastMessageTime": 1690974960683062,
      "isItSavedContact": false,
      "isConversationUnRead": false,
      "lastMessageStatus": 1,
      "profileThumbImage": "",
      "lastMessageContent": "",
      "isSelected": false,
      "jid": "919789921025@xmpp-uikit-qa.contus.us",
      "profileType": "singlechat",
      "lastMessageType": "text",
      "isGroupInOfflineMode": false,
      "isDeletedUser": false,
      "isBroadCast": false,
      "isChatArchived": false,
      "topicID": "",
      "isMentionedUser": false,
      "mentionedUsersIds": [],
      "isChatPinned": false,
      "isLastMessageRecalledByUser": false,
      "isBlocked": false,
      "isLastMessageSentByMe": true,
      "profileName": "Iv0XaLzMwy922KFjAyYpCQ==",
      "isMuted": false,
      "unreadMessageCount": 0,
      "isBlockedMe": false
    }
  ]
}""";
    var response = convertRecentChatJsonFromString(output);
    debugPrint(response);
  });

  test("getGroupMembersList", () {
      var output = """[
  {
    "contactType": "unknown_contact",
    "email": "mr.saravana139@gmail.com",
    "groupCreatedTime": "919789482015",
    "image": "9197894820151688137906046IJ1R2XeKUo0b8h0W9T71.",
    "imagePrivacyFlag": "",
    "isAdminBlocked": false,
    "isBlocked": false,
    "isBlockedMe": false,
    "isGroupAdmin": true,
    "isGroupInOfflineMode": false,
    "isGroupProfile": false,
    "isItSavedContact": false,
    "isMuted": false,
    "isSelected": false,
    "jid": "919789482015@xmpp-uikit-qa.contus.us",
    "lastSeenPrivacyFlag": "",
    "mobileNUmberPrivacyFlag": "",
    "mobileNumber": "919789482015",
    "name": "Muthupandi4",
    "nickName": "Muthupandi4",
    "status": "I am in Mirror Fly",
    "thumbImage": ""
  },
  {
    "contactType": "unknown_contact",
    "email": "goat@ags.com",
    "groupCreatedTime": "9876543210",
    "image": "9198765432101704350526763myM3aN80GCbYQooh0df3.jpg",
    "imagePrivacyFlag": "",
    "isAdminBlocked": false,
    "isBlocked": false,
    "isBlockedMe": false,
    "isGroupAdmin": true,
    "isGroupInOfflineMode": false,
    "isGroupProfile": false,
    "isItSavedContact": false,
    "isMuted": false,
    "isSelected": false,
    "jid": "919876543210@xmpp-uikit-qa.contus.us",
    "lastSeenPrivacyFlag": "",
    "mobileNUmberPrivacyFlag": "",
    "mobileNumber": "9876543210",
    "name": "GOAT",
    "nickName": "919876543210",
    "status": "I am in Mirror Fly",
    "thumbImage": ""
  },
  {
    "contactType": "unknown_contact",
    "email": "saravanakumar.b@contus.in",
    "groupCreatedTime": "919894940560",
    "image": "9198949405601700145240822tI49m0XLeRX62d1BJUg7.",
    "imagePrivacyFlag": "",
    "isAdminBlocked": false,
    "isBlocked": false,
    "isBlockedMe": false,
    "isGroupAdmin": false,
    "isGroupInOfflineMode": false,
    "isGroupProfile": false,
    "isItSavedContact": false,
    "isMuted": false,
    "isSelected": false,
    "jid": "919894940560@xmpp-uikit-qa.contus.us",
    "lastSeenPrivacyFlag": "",
    "mobileNUmberPrivacyFlag": "",
    "mobileNumber": "919894940560",
    "name": "Sk2",
    "nickName": "919894940560",
    "status": "I am in MirrorFly",
    "thumbImage": ""
  },
  {
    "email": "flutterteam@gmail.com",
    "image": "91888345246117042028323628560k3VCf8O1J0BCE0o3.jpg",
    "isAdminBlocked": false,
    "isBlocked": false,
    "isBlockedMe": false,
    "isGroupAdmin": false,
    "isGroupInOfflineMode": false,
    "isGroupProfile": false,
    "isItSavedContact": false,
    "isMuted": false,
    "isSelected": false,
    "jid": "918883452461@xmpp-uikit-qa.contus.us",
    "name": "You",
    "nickName": "You",
    "status": "I am in Mirror Fly"
  }
]""";
      var response = convertGroupMembersJsonFromString(output);
      debugPrint(response);
  });
}
