//
//  FlyMethods.swift
//  mirrorfly_plugin
//
//  Created by Mani Vendhan on 15/06/23.
//

import Foundation
import Flutter

class FlyMethodConstants {

    static let flyCallMethods = FlyCallMethods.shared
    static let callMethodHandlers: [String: (FlutterMethodCall, @escaping FlutterResult, MirrorflyViewFactory?) -> Void] = {
        return [
            "getCallUsersList": flyCallMethods.getCallUsersList,
            "getAudioDevices": flyCallMethods.getAudioDevices,
            "makeVoiceCall": flyCallMethods.makeVoiceCall,
            "makeVideoCall": flyCallMethods.makeVideoCall,
//            "answerCall": flyCallMethods.answerCall,
            "declineCall": flyCallMethods.declineCall,
            "muteAudio": flyCallMethods.muteAudio,
//            "isVideoMuted": flyCallMethods.isVideoMuted,
//            "isRemoteVideoMuted": flyCallMethods.isRemoteVideoMuted,
//            "isRemoteVideoPaused": flyCallMethods.isRemoteVideoPaused,
            "makeGroupVideoCall": flyCallMethods.makeGroupVideoCall,
            "makeGroupVoiceCall": flyCallMethods.makeGroupVoiceCall,
            "switchCamera": flyCallMethods.switchCamera,
            "isCallOnHold": flyCallMethods.isCallOnHold,
            "isOneToOneCall": flyCallMethods.isOneToOneCall,
            "getCallType": flyCallMethods.getCallType,
            "getGroupID": flyCallMethods.getGroupID,
            "isCallConnected": flyCallMethods.isCallConnected,
            "isVideoCall": flyCallMethods.isVideoCall,
            "isAudioCall": flyCallMethods.isAudioCall,
            "isCallNotConnected": flyCallMethods.isCallNotConnected,
            "isUserAudioMuted": flyCallMethods.isUserAudioMuted,
            "isUserVideoMuted": flyCallMethods.isUserVideoMuted,
            "inviteUsersToOngoingCall": flyCallMethods.inviteUsersToOngoingCall,
            "getCallDirection": flyCallMethods.getCallDirection,
            "getAllAvailableAudioInput": flyCallMethods.getAllAvailableAudioInput,
            "routeAudioTo": flyCallMethods.routeAudioTo,
            "isOnGoingCall": flyCallMethods.isOnGoingCall,
            "muteVideo": flyCallMethods.muteVideo,
            "getUnreadMissedCallCount": flyCallMethods.getUnreadMissedCallCount,
            "requestVideoCallSwitch": flyCallMethods.requestVideoCallSwitch,
            "cancelVideoCallSwitch": flyCallMethods.cancelVideoCallSwitch,
            "acceptVideoCallSwitchRequest": flyCallMethods.acceptVideoCallSwitchRequest,
            "declineVideoCallSwitchRequest": flyCallMethods.declineVideoCallSwitchRequest,
            "getMaxCallUsersCount": flyCallMethods.getMaxCallUsersCount,
            "getInvitedUsersList": flyCallMethods.getInvitedUsersList,
            "getCallLogsList": flyCallMethods.getCallLogsList,
            "deleteCallLog": flyCallMethods.deleteCallLog,
            "syncCallLogs": flyCallMethods.syncCallLogs,
            "isCallConversionRequestAvailable": flyCallMethods.isCallConversionRequestAvailable,
            "getLocalCallLogs": flyCallMethods.getLocalCallLogs,
            "markAllUnreadMissedCallsAsRead": flyCallMethods.markAllUnreadMissedCallsAsRead,
            "createMeetLink": flyCallMethods.createMeetLink,
            "initializeMeet": flyCallMethods.initializeMeet,
            "getCallLink": flyCallMethods.getCallLink,
            "disposePreview": flyCallMethods.disposePreview,
            "joinCall": flyCallMethods.joinCall,
            "startVideoCapture": flyCallMethods.startVideoCapture,
            
        ]
    }()
    
    static let flyChatMethods = FlyChatMethods.shared
        
        static let chatMethodHandlers: [String: (FlutterMethodCall, @escaping FlutterResult) -> Void] = {
            return [
                "init": flyChatMethods.buildChatSDK,
                "initializeSDK": flyChatMethods.initializeSDK,
                "getPlistValue": flyChatMethods.getPlistValue,
    //            "contactSyncStateValue": flyChatMethods.contactSyncStateValue,
                "revokeContactSync": flyChatMethods.revokeContactSync,
                "getUsersWhoBlockedMe": flyChatMethods.getUsersWhoBlockedMe,
                "getUnKnownUserProfiles": flyChatMethods.getUnKnownUserProfiles,
                "getMyProfileStatus": flyChatMethods.getMyProfileStatus,
                "getMyBusyStatus": flyChatMethods.getMyBusyStatus,
                "setMyBusyStatus": flyChatMethods.setMyBusyStatus,
                "enableDisableBusyStatus": flyChatMethods.enableDisableBusyStatus,
                "getBusyStatusList": flyChatMethods.getBusyStatusList,
                "deleteProfileStatus": flyChatMethods.deleteProfileStatus,
                "deleteBusyStatus": flyChatMethods.deleteBusyStatus,
                "enableDisableHideLastSeen": flyChatMethods.enableDisableHideLastSeen,
                "isHideLastSeenEnabled": flyChatMethods.isHideLastSeenEnabled,
                "deleteMessagesForMe": flyChatMethods.deleteMessagesForMe,
                "deleteMessagesForEveryone": flyChatMethods.deleteMessagesForEveryone,
                "markAsRead": flyChatMethods.markAsRead,
                "markConversationAsUnread": flyChatMethods.markConversationAsUnread,
                "markConversationAsRead": flyChatMethods.markConversationAsRead,
                "deleteUnreadMessageSeparatorOfAConversation": flyChatMethods.deleteUnreadMessageSeparatorOfAConversation,
                "getRecalledMessagesOfAConversation": flyChatMethods.getRecalledMessagesOfAConversation,
                "uploadMedia": flyChatMethods.uploadMedia,
                "getMessagesUsingIds": flyChatMethods.getMessagesUsingIds,
                "updateMediaDownloadStatus": flyChatMethods.updateMediaDownloadStatus,
                "updateMediaUploadStatus": flyChatMethods.updateMediaUploadStatus,
                "cancelMediaUploadOrDownload": flyChatMethods.cancelMediaUploadOrDownload,
                "setMediaEncryption": flyChatMethods.setMediaEncryption,
                "deleteAllMessages": flyChatMethods.deleteAllMessages,
                "getGroupJid": flyChatMethods.getGroupJid,
                "getProfileDetails": flyChatMethods.getProfileDetails,
                "getGroupProfile": flyChatMethods.getGroupProfile,
                "getProfileStatusList": flyChatMethods.getProfileStatusList,
                
                "insertDefaultStatus": flyChatMethods.insertDefaultStatus,
                "getRingtoneName": flyChatMethods.getRingtoneName,
                "setOnGoingChatUser": flyChatMethods.setOnGoingChatUser,
                "markAsReadDeleteUnreadSeparator": flyChatMethods.markAsReadDeleteUnreadSeparator,
                "getMessagesOfJid": flyChatMethods.getMessagesOfJid,
                "updateRecentChatPinStatus": flyChatMethods.updateRecentChatPinStatus,
                "deleteRecentChat": flyChatMethods.deleteRecentChat,
                "recentChatPinnedCount": flyChatMethods.recentChatPinnedCount,
                "getRecentChatList": flyChatMethods.getRecentChatList,
                "getRecentChatListHistory": flyChatMethods.getRecentChatListHistory,
                "getRecentChatListHistoryByTopic": flyChatMethods.getRecentChatListHistoryByTopic,
                "getRecentChatListIncludingArchived": flyChatMethods.getRecentChatListIncludingArchived,
                "getRecentChatOf": flyChatMethods.getRecentChatOf,
                "register_user": flyChatMethods.registerUser,
                "authtoken": flyChatMethods.refreshAndGetAuthToken,
                "refreshAuthToken": flyChatMethods.refreshAndGetAuthToken,
                "verifyToken": flyChatMethods.verifyToken,
                "get_jid": flyChatMethods.getJid,
                "send_text_msg": flyChatMethods.sendTextMessage,
                "sendLocationMessage": flyChatMethods.sendLocationMessage,
                "send_image_message": flyChatMethods.sendImageMessage,
                "send_video_message": flyChatMethods.sendVideoMessage,
                "sendContactMessage": flyChatMethods.sendContactMessage,
                "sendDocumentMessage": flyChatMethods.sendDocumentMessage,
                "sendAudioMessage": flyChatMethods.sendAudioMessage,
                "get_user_list": flyChatMethods.getUserList,
                "getRegisteredUsers": flyChatMethods.getRegisteredUsers,
                "getUserProfile": flyChatMethods.getUserProfile,
                "clear_chat": flyChatMethods.clearChat,
                "updateMyProfile": flyChatMethods.updateMyProfile,
                "media_endpoint": flyChatMethods.getMediaEndPoint,
                "reportUserOrMessages": flyChatMethods.reportUserOrMessages,
                "block_user": flyChatMethods.blockUser,
                "un_block_user": flyChatMethods.unblockUser,
                "createGroup": flyChatMethods.createGroup,
                "getUserLastSeenTime": flyChatMethods.getUserLastSeenTime,
                "getUsersIBlocked": flyChatMethods.getUsersIBlocked,
                "setMyProfileStatus": flyChatMethods.setMyProfileStatus,
                "getMediaMessages": flyChatMethods.getMediaMessages,
                "isMemberOfGroup": flyChatMethods.isMemberOfGroup,
                "updateArchiveUnArchiveChat": flyChatMethods.updateArchiveUnArchiveChat,
                "getArchivedChatList": flyChatMethods.getArchivedChatList,
                "updateChatMuteStatus": flyChatMethods.updateChatMuteStatus,
                "updateChatMuteStatusList": flyChatMethods.updateChatMuteStatusList,
                "sendTypingStatus": flyChatMethods.sendTypingStatus,
                "sendTypingGoneStatus": flyChatMethods.sendTypingGoneStatus,
                "setNotificationSound": flyChatMethods.setNotificationSound,
                "isBusyStatusEnabled": flyChatMethods.isBusyStatusEnabled,
                "updateMyProfileImage": flyChatMethods.updateMyProfileImage,
                "isUserUnArchived": flyChatMethods.isUserUnArchived,
                "forwardMessagesToMultipleUsers": flyChatMethods.forwardMessagesToMultipleUsers,
                "removeProfileImage": flyChatMethods.removeProfileImage,
                "isArchivedSettingsEnabled": flyChatMethods.isArchivedSettingsEnabled,
                "getGroupMembersList": flyChatMethods.getGroupMembersList,
                "enableDisableArchivedSettings": flyChatMethods.enableDisableArchivedSettings,
                "clearAllConversation": flyChatMethods.clearAllConversation,
                "insertBusyStatus": flyChatMethods.insertBusyStatus,
                "getDocsMessages": flyChatMethods.getDocsMessages,
                "getLinkMessages": flyChatMethods.getLinkMessages,
                "isAdmin": flyChatMethods.isAdmin,
                "leaveFromGroup": flyChatMethods.leaveFromGroup,
                "getMediaAutoDownload": flyChatMethods.getMediaAutoDownload,
                "setMediaAutoDownload": flyChatMethods.setMediaAutoDownload,
                "getMediaSetting": flyChatMethods.getMediaSetting,
                "saveMediaSettings": flyChatMethods.saveMediaSettings,
                "downloadMedia": flyChatMethods.downloadMedia,
                "updateFavouriteStatus": flyChatMethods.updateFavouriteStatus,
                "iOSFileExist": flyChatMethods.iOSFileExist,
                "get_favourite_messages": flyChatMethods.getFavouriteMessages,
                "getUnsentMessageOfAJid": flyChatMethods.getUnsentMessageOfAJid,
                "getUnsentMessageOf": flyChatMethods.getUnsentMessageOf,
                "saveUnsentMessage": flyChatMethods.saveUnsentMessage,
                "deleteRecentChats": flyChatMethods.deleteRecentChats,
                "getDefaultNotificationUri": flyChatMethods.getDefaultNotificationUri,
                "logoutOfChatSDK": flyChatMethods.logoutOfChatSDK,
                "getMessageOfId": flyChatMethods.getMessageOfId,
                "insertNewProfileStatus": flyChatMethods.insertNewProfileStatus,
                "IS_TRIAL_LICENSE": flyChatMethods.isTrailLicence,
                "makeAdmin": flyChatMethods.makeAdmin,
                "updateGroupName": flyChatMethods.updateGroupName,
                "updateGroupProfileImage": flyChatMethods.updateGroupProfileImage,
                "removeGroupProfileImage": flyChatMethods.removeGroupProfileImage,
                "addUsersToGroup": flyChatMethods.addUsersToGroup,
                "removeMemberFromGroup": flyChatMethods.removeMemberFromGroup,
                "isMuted": flyChatMethods.isMuted,
                "exportChatConversationToEmail": flyChatMethods.exportChatConversationToEmail,
                "getAllGroups": flyChatMethods.getAllGroups,
                "searchConversation": flyChatMethods.searchConversation,
                "delete_account": flyChatMethods.deleteAccount,
                "getGroupMessageDeliveredToList": flyChatMethods.getGroupMessageDeliveredToList,
                "getGroupMessageReadByList": flyChatMethods.getGroupMessageReadByList,
                "setDefaultNotificationSound": flyChatMethods.setDefaultNotificationSound,
                "deleteGroup": flyChatMethods.deleteGroup,
                "getMessageStatusOfASingleChatMessage": flyChatMethods.getMessageStatusOfASingleChatMessage,
                "addContact": flyChatMethods.addContact,
                "initializeMessageList": flyChatMethods.initializeMessageList,
                "loadMessages": flyChatMethods.loadMessages,
                "loadPreviousMessages": flyChatMethods.loadPreviousMessages,
                "loadNextMessages": flyChatMethods.loadNextMessages,
                "handleReceivedMessage": flyChatMethods.handleReceivedMessage,
                "updateFcmToken": flyChatMethods.updateFcmToken,
                "getUnreadMessageCountExceptMutedChat": flyChatMethods.getUnreadMessageCountExceptMutedChat,
                "createTopic": flyChatMethods.createTopic,
                "getTopics": flyChatMethods.getTopics,
                "getAvailableFeatures": flyChatMethods.getAvailableFeatures,
                "appLaunchedFromMissedCall": flyChatMethods.appLaunchedFromMissedCall,
                "setRegionCode": flyChatMethods.setRegionCode,
                "hasPreviousMessages": flyChatMethods.hasPreviousMessages,
                "hasNextMessages": flyChatMethods.hasNextMessages,
                "getCurrentAuthToken": flyChatMethods.getCurrentAuthToken,
                "sendMessage": flyChatMethods.sendMessage,
                "unFavouriteAllFavouriteMessages": flyChatMethods.unFavouriteAllFavouriteMessages,
                "getUnreadMessagesCount": flyChatMethods.getUnreadMessagesCount,
                "loginWebChatViaQRCode": flyChatMethods.loginWebChatViaQRCode,
                "webLoginDetailsCleared": flyChatMethods.webLoginDetailsCleared,
                "getWebLoginDetails": flyChatMethods.getWebLoginDetails,
                "logoutWebUser": flyChatMethods.logoutWebUser,
                "sendContactUsInfo": flyChatMethods.sendContactUsInfo,
                "getJidFromPhoneNumber": flyChatMethods.getJidFromPhoneNumber,
                "editTextMessage": flyChatMethods.editTextMessage,
                "editMediaCaption": flyChatMethods.editMediaCaption,
                "appLaunchedDetails": flyChatMethods.appLaunchedDetails,
                "getMetaData": flyChatMethods.getMetaData,
                "updateMetaData": flyChatMethods.updateMetaData,
                "isPrivateStorageEnabled": flyChatMethods.isPrivateStorageEnabled,
                "startBackup": flyChatMethods.startBackup,
                "restoreBackup": flyChatMethods.restoreBackup,
                "cancelBackup": flyChatMethods.cancelBackup,
                "cancelRestore": flyChatMethods.cancelRestore,
            ] }()
}
